Complete GitHub Actions with seperate unit and integration test reports.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,10 +1,6 @@
 name: Java CI
 
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+on: push
 
 jobs:
   build:
@@ -12,22 +8,21 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up JDK 17
-        uses: actions/setup-java@v2
+        uses: actions/setup-java@v3
         with:
           distribution: 'adopt'
           java-version: '17'
 
       - name: Cache Maven packages
-        uses: actions/cache@v2
+        uses: actions/cache@v3
         with:
           path: ~/.m2
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
-
       - name: Install dependencies
         run: mvn install -DskipTests
 
@@ -37,17 +32,34 @@ jobs:
       - name: Run integration tests
         run: mvn verify -Dtest=*IntegrationTest
 
-      - name: Upload test results
+      - name: Upload unit test results
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: test-results
+          name: unit-test-results
           path: target/surefire-reports/*.xml
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
+      - name: Upload integration test results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: integration-test-results
+          path: target/surefire-reports/*.xml
+
+      - name: Publish Unit Test Report
+        uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
         with:
-          report_paths: "**/target/surefire-reports/TEST-*.xml"
+          report_paths: "**/target/surefire-reports/TEST-*UnitTest.xml"
           detailed_summary: true # display detailed summary of the report
           include_passed: true # include passed tests in the results table
+          title: "Unit Test Report"
+
+      - name: Publish Integration Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "**/target/surefire-reports/TEST-*IntegrationTest.xml"
+          detailed_summary: true # display detailed summary of the report
+          include_passed: true # include passed tests in the results table
+          title: "Integration Test Report"
